server:
  port: 80

logging:
  level:
    org.hibernate: info

jasypt:
  encryptor:
  bean: jasyptStringEncryptor

spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(0eWswqteVmFlYAAZy2nhW3OY9tsKyrmfIHkyf/ApbgUASUfbKudFKMX0Pg4dnDOwfKQBO7AmgCjz728GORzU7JD315obEnAGs353o5CbHoV0V9nzxKhLW8qnaByKWjDDriyWeZYSAF0yXUcuWWxM0w==)
    username: ENC(+9Nw3I61uDxJYl7mVdVzqg==)
    password: ENC(3dKqgYYH8OS44BKhIGNxcnQfUE9o1qAr)

  jpa:
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

serverTimezone: Asia/Seoul
